### PR TITLE
Don't override initialize method

### LINKED ISSUE #15: Problems with initialization from nested attributes
If a record is initialized using [nested attributes](https://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html), `#initialize` complains about having the wrong number of arguments.

### PR DESCRIPTION
**Pull request by boardfish**
As it turns out, overriding `initialize` for `ActiveRecord::Base` is a bad idea. So instead we're introducing a transient attribute that we'll default to `true` after initialize.

Closes #15

### CODE REVIEW

File: lib/remote_record/reference.rb [hunk 1]
```diff
@@ -29,7 +29,10 @@ def remote_record_config
     included do
       attr_accessor :fetching
 
+      scope :skip_fetching, -> { where(fetching: false) }
```
Comment (johndbritton) [inline lib/remote_record/reference.rb:32]: I'm not quite sure I understand why a reference would have a column called `fetching`

Comment (johndbritton) [reply lib/remote_record/reference.rb:32]: And also unclear to me why this would involve a `scope`

File: spec/remote_record_spec.rb [hunk 2]
```diff
@@ -36,6 +36,37 @@ def client
     initialize_reference
   end
 
+  describe '#skip_fetching' do
+    before do
+      skip 'relies on database'
```
Comment (johndbritton) [inline spec/remote_record_spec.rb:41]: I don't quite understand what this is doing

**Review by johndbritton — COMMENTED** [review]
I don't quite understand this change

File: lib/remote_record/reference.rb (hunk 1 above)
Comment (boardfish) [reply lib/remote_record/reference.rb:32]: `fetching` isn't a column, it's a transient attribute - it's stored on the instance, but not in the database.

The scope is necessary so that records can be instantiated from an `ActiveRecord::Relation` with the transient attribute set.

File: spec/remote_record_spec.rb (hunk 2 above)
Comment (boardfish) [reply spec/remote_record_spec.rb:41]: These tests are necessary for that scope, but we can't put them to work just yet because we don't have a database backing the tests.

**Review by johndbritton — APPROVED** [review]
